lawpact/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lawpact.views.home', name='home'),
    # url(r'^lawpact/', include('lawpact.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('contract.urls')),
)

rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^category/(?P<category_name_url>\w+)/$', views.category, name='category'))

contract/models.py
# coding=utf-8

from django.db import models
from django.contrib.auth.models import User

from django.utils.translation import ugettext_lazy as _

USER_PROPERTY_CHOICES = (
    ('0', u'个人'),
    ('1', u'公司'),
    ('2', u'工作室'),
    ('3', u'其他'),
)

USER_OCCUPATION_CHOICES = (
    ('0', u'编剧'),
    ('1', u'导演'),
    ('2', u'演员'),
    ('3', u'经纪人'),
    ('4', u'制片人'),
    ('5', u'策划'),
    ('6', u'宣传'),
    ('7', u'发行'),
    ('8', u'法务/律师'),
    ('7', u'其他'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, verbose_name=u"用户")
    pic = models.ImageField(u"头像", upload_to='images', blank=True)
    contract_url = models.URLField(blank=True)
    
    #For user active by the email
    activation_key = models.CharField(max_length=40, null=True, blank=True)
    key_expires = models.DateTimeField(blank=True, null=True)
    
    #detailed info
    real_name = models.CharField(u'姓名', max_length=10, blank=True)
    phone_number = models.CharField(u"电话号码", max_length=15, blank=True)
    
    #optional info
    property = models.CharField(verbose_name = u"用户性质", max_length=1, choices=USER_PROPERTY_CHOICES, blank=True)
    #occupation = models.CharField(verbose_name = u"职业", max_length=1, choices=USER_OCCUPATION_CHOICES, blank=True)
    
    bianju = models.BooleanField(u"编剧", blank=True)
    daoyan = models.BooleanField(u"导演", blank=True)
    yanyuan = models.BooleanField(u"演员", blank=True)
    jingjiren = models.BooleanField(u"经纪人", blank=True)
    zhipianren = models.BooleanField(u"制片人", blank=True)
    cehua = models.BooleanField(u"策划", blank=True)
    xuanchuan = models.BooleanField(u"宣传", blank=True)
    faxing = models.BooleanField(u"发行", blank=True)
    fawu = models.BooleanField(u"法务/律师", blank=True)
    qita = models.BooleanField(u"其他", blank=True)
    
    #Company related info
    company_name = models.CharField(u'公司名称', max_length=50, blank=True)
    company_address = models.CharField(u'公司地址', max_length=100, blank=True)
    company_email = models.EmailField(u'公司邮箱', blank=True)
   
    class Meta:
        verbose_name = u"1.注册用户信息"
        verbose_name_plural = u"1.注册用户信息"
    
    def __unicode__(self):
        return self.user.username
    
CONTRACT_STATUS_CHOICES = (
    ('0', u'未审核'),
    ('1', u'已审核'),
    ('2', u'审核中'),
)

LAW_STATUS_CHOICES = (
    ('0', u'已生效'),
    ('1', u'已终止'),

)

def user_file_folder(instance, filename):
    #return "files/user_%s/%s" % (instance.user.id, filename)
    return "files/%s/%s" % (instance.user.id, filename)
    #print 'files/user_{0}/{1}' % (instance.user.id, filename)
    #return "files/user_{0}/{1}" % (instance.user.id, filename)
class UserContract(models.Model):
    user = models.ForeignKey(User)
    contract_id = models.CharField(max_length=25, verbose_name=u"合同编号", blank=True)
    name = models.CharField(max_length=50, verbose_name=_('name'))
    type = models.CharField(max_length=20, verbose_name=u"合同类型", blank=True)
    #contract_status = models.BooleanField(verbose_name = u"合同状态", blank=True)
    contract_status = models.CharField(verbose_name = u"合同状态", max_length=1, choices=CONTRACT_STATUS_CHOICES, blank=True)
    law_status = models.CharField(verbose_name = u"法律状态", max_length=1, choices=LAW_STATUS_CHOICES, blank=True)
    label = models.CharField(verbose_name = u"标签", max_length=10, blank=True)

    #backlog_date = models.DateField()
    #backlog = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    #file = models.FileField(upload_to='files', blank=True)
    file = models.FileField(upload_to=user_file_folder)
    create_at = models.DateField(verbose_name = u"创建时间", auto_now_add = True, blank=True)
    
    class Meta:
        verbose_name = u"2.合同信息"
        verbose_name_plural = u"2.合同信息"
    
    def __unicode__(self):
        return self.name

class Backlog(models.Model):
    user = models.ForeignKey(User)
    start_date = models.DateField(blank=True)
    end_date = models.DateField(blank=True)
    back_color = models.CharField(max_length=20, blank=True)
    description = models.CharField(max_length = 300, blank=True)
    contract_name = models.CharField(max_length = 50, blank=True)
    
    class Meta:
        verbose_name = u"3.待办事项列表"
        verbose_name_plural = u"3.待办事项列表"
    
    def __unicode__(self):
        return self.user.username

templates/previous/about - 副本.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>关于我们</title>
    <meta name="description" content="有娱-关于我们">
    <meta name="author" content="xiao kai, peng">

    <!-- 导入Roboto字体
    <link rel="stylesheet" href="http://fonts.useso.com/css?family=Roboto:400,100,300,500"> -->
    <!-- 导入noto sans sc字体
    <link rel="stylesheet" href="http://fonts.useso.com/earlyaccess/notosanssc.css"> -->

	<link href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href="../static/css/style.css">
	<link rel="stylesheet" href="../static/css/about.css">

    <!-- 加载各种icon -->
    <link rel="icon" href="../static/img/logo.ico">
    <link rel="shortcut icon" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" href="../static/img/logo.ico">


</head>

<body>
	<header>
		<!-- 置顶导航 -->
		<nav role="navigation" class="navbar navbar-static-top">
			<div class="container">
				<a class="brand" href="#">
					<img alt="Brand" src="../static/img/logo.ico">
				</a>

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_top_navbar" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<div class="collapse navbar-collapse" id="main_top_navbar">
					<!-- 以下填充置顶导航中的链接 -->
					<ul class="nav navbar-nav navbar-left">
						<li>
							<a href="./index.html">首&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;页</a>
						</li>
						<li>
							<a href="./contract-guider.html">合同生成</a>
						</li>
						<li>
							<a href="./contract-info.html">合同管理</a>
						</li>
						<li>
							<a href="./about.html">联系我们</a>
						</li>
					</ul>

					<!-- 这里是登录的按钮或者用户管理的下拉菜单 -->
					<!-- 这里示例下拉菜单 -->
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								用户名
								<img src="../static/img/avatar.jpg" class="avatar">
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="./user-info.html">个人资料</a></li>
								<li><a href="./contract-info.html">我的合同</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">退出登录</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<main class="body-wrapper">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<ul class="nav nav-tabs nav-pills nav-stacked" role="tablist">
						<li role="presentation" class="active"><a href="#section-1" aria-controls="section-1" role="tab" data-toggle="tab">关于我们</a></li>
						<li role="presentation"><a href="#section-2" aria-controls="section-2" role="tab" data-toggle="tab">商务合作</a></li>
						<li role="presentation"><a href="#section-3" aria-controls="section-3" role="tab" data-toggle="tab">免责声明</a></li>
						<li role="presentation"><a href="#section-4" aria-controls="section-4" role="tab" data-toggle="tab">联系我们</a></li>
						<li role="presentation"><a href="#section-5" aria-controls="section-5" role="tab" data-toggle="tab">帮助</a></li>
					</ul>
				</div>
				<div id="about" class="col-sm-9">
					<div class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="section-1">
							<fieldset>
								<legend>关于我们</legend>
							</fieldset>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="section-2">
							<fieldset>
								<legend>商务合作</legend>
							</fieldset>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="section-3">
							<fieldset>
								<legend>免责声明</legend>
							</fieldset>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="section-4">
							<fieldset>
								<legend>联系我们</legend>
							</fieldset>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="section-5">
							<fieldset>
								<legend>帮助</legend>
							</fieldset>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>

	<footer>
		<div class="container">
			<div class="footer-border"></div>
			<div class="row">
				<div class="col-sm-4">
					<p>Copyright  2016 有娱. All Rights Reserved</p>
				</div>
				<div class="col-sm-4">
					<div class="bdsharebuttonbox">
						<a href="#" class="fa fa-qq" data-cmd="tqq"></a>
						<a href="#" class="fa fa-weixin" data-cmd="weixin"></a>
						<a href="#" class="fa fa-weibo" data-cmd="tsina"></a>
					</div>
				</div>
				<div class="col-sm-4">
					<ul class="info">
						<li><span class="fa fa-question-circle"></span><a href="./about.html">关于我们</a></li>
						<li><span class="fa fa-user-plus"></span><a href="./about.html">商务合作</a></li>
						<li><span class="fa fa-info-circle"></span><a href="./about.html">免责声明</a></li>
						<li><span class="fa fa-envelope"></span><a href="./about.html">联系我们</a></li>
						<li><span class="fa fa-h-square"></span><a href="./about.html">帮助</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- 返回顶部悬浮按钮 -->
	<span id="top-link-block" class="hidden">
	    <a href="#top" class="well well-sm" onclick="$('html,body').animate({scrollTop:0},'fast');return false;">
	        <i class="fa fa-arrow-up"></i>返回顶部
	    </a>
	</span>

	<!-- 加载JS -->
	<script src="https://cdn.bootcss.com/jquery/1.12.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="../static/js/script.js"></script>
</body>
</html>

templates/previous/contract-info - 副本.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>合同管理</title>
    <meta name="description" content="有娱-合同管理">
    <meta name="author" content="xiao kai, peng">

    <!-- 导入Roboto字体
    <link rel="stylesheet" href="http://fonts.useso.com/css?family=Roboto:400,100,300,500"> -->
    <!-- 导入noto sans sc字体
    <link rel="stylesheet" href="http://fonts.useso.com/earlyaccess/notosanssc.css"> -->

	<link href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<link href="https://cdn.bootcss.com/fullcalendar/2.6.1/fullcalendar.min.css" rel="stylesheet">
	<link rel="stylesheet" href="../static/css/style.css">
	<link rel="stylesheet" href="../static/css/contract-info.css">

    <!-- 加载各种icon -->
    <link rel="icon" href="../static/img/logo.ico">
    <link rel="shortcut icon" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../static/img/logo.ico">
    <link rel="apple-touch-icon-precomposed" href="../static/img/logo.ico">


</head>

<body>
	<header>
		<!-- 置顶导航 -->
		<nav role="navigation" class="navbar navbar-static-top">
			<div class="container">
				<a class="brand" href="#">
					<img alt="Brand" src="../static/img/logo.ico">
				</a>

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_top_navbar" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<div class="collapse navbar-collapse" id="main_top_navbar">
					<!-- 以下填充置顶导航中的链接 -->
					<ul class="nav navbar-nav navbar-left">
						<li>
							<a href="./index.html">首&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;页</a>
						</li>
						<li>
							<a href="./contract-guider.html">合同生成</a>
						</li>
						<li>
							<a href="./contract-info.html">合同管理</a>
						</li>
						<li>
							<a href="./about.html">联系我们</a>
						</li>
					</ul>

					<!-- 这里是登录的按钮或者用户管理的下拉菜单 -->
					<!-- 这里示例下拉菜单 -->
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								用户名
								<img src="../static/img/avatar.jpg" class="avatar">
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="./user-info.html">个人资料</a></li>
								<li><a href="./contract-info.html">我的合同</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="#">退出登录</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<main class="body-wrapper">
		<div class="container">
			<div class="row">
				<div class="col-sm-12" id="doc-info-view">
					<ul class="nav nav-tabs" id="switch-bar">
						<li role="presentation" class="active"><a href="#table-view" aria-controls="home" role="tab" data-toggle="tab">合同</a></li>
						<li role="presentation"><a href="#calendar-view" aria-controls="profile" role="tab" data-toggle="tab">日历</a></li>
					</ul>

					<div class="tab-content">
						<div role="tabpanel" class="tab-pane active" id="table-view">
							<div class="row">
								<div class="col-sm-12">
									<div class="form-box">
										<div class="form-top">
											<div class="form-top-left">
												<h3 class="default-h3">
													合同列表
												</h3>
												<p>
													编辑合同名称和标签，修改法律状态
												</p>
											</div>
											<div class="form-top-right">
												<i class="fa fa-table"></i>
											</div>
										</div>
										<div class="form-bottom">
										    <div class="input-group search_div">
										      <input type="search" class="form-control" placeholder="可按编号、名称、标签等搜索您的合同...">
										      <span class="input-group-btn">
										        <button class="btn btn-default search_btn" type="button"><span class="fa fa-search"></span></button>
										      </span>
										    </div>
											<div>
												<table class="table info">
													<caption>您共有30份合同，显示第1-10份合同...</caption>
													<thead>
														<tr>
															<th>合同编号</th>
															<th>合同名称</th>
															<th>合同类型</th>
															<th>状态</th>
															<th>法律状态</th>
															<th>标签</th>
															<th>操作</th>
														</tr>
													</thead>
													<tbody>
													{% for obj in objs %}
														<tr>
															<td>{{ obj.id }}</td>
															<td><input type="text" name="name" value="{{ obj.name }}"></td>
															<td>{{ obj.type }}</td>
															<td>{{ obj.get_contract_status_display }} 
															</td>
															<td>
																<select name="status" class="table_select">
																	<option value="0" class="label label-success">已生效</option>
																	<option value="1" class="label label-danger">已终止</option>
																</select>
															</td>
															<td><input type="text" name="lable" placeholder="未设置"></td>
															<td>
																<div class="btn-group">
																	<button type="button" class="btn btn-default activation dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">操作
																		<span class="caret"></span>
																	</button>
																	<ul class="dropdown-menu">
																		<li><a class="preview" href="/preview-contract/{{ obj.id }}">预览/下载</a></li>
																		<li><button type="button" class="btn btn-default preview">提交审核</button></li>
																		<li role="separator" class="divider"></li>
																		<li><button type="button" class="btn btn-default delete" href="/contract/delete/{{obj.id}}">删除</button></li>
																	</ul>
																</div>
															</td>
														</tr>
													{% endfor %}
													</tbody>
												</table>
											</div>
											<div class="row">
												<div class="col-sm-1 col-sm-offset-1">
													<button type="button" class="btn btn-default prev">上一页</button>
												</div>
												<div class="col-sm-1 col-sm-offset-8">
													<button type="button" class="btn btn-default next">下一页</button>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div role="tabpanel" class="tab-pane" id="calendar-view">
							<div class="row">
								<div class="col-sm-12">
									<div id="calendar">
									</div>

									<div class="modal fade" id="add-event" tabindex="-1" role="dialog" aria-labelledby="Label">
										<div class="modal-dialog" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal" aria-label="关闭">
														<span aria-hidden="true">&times;</span>
													</button>
													<h4 class="modal-title" id="Label">添加事件</h4>
												</div>
												<div class="modal-body">
								                    <input hidden name="id"/>
													<div class="form-group">
														<label for="script-content" class="sr-only">事件说明</label>
														<textarea name="title" placeholder="事件说明" class="form-control"></textarea>
													</div>
													<div class="form-group">
										                <div class='input-group date' id='datetimepicker1'>
										                	<label for="script-name" class="sr-only">开始时间</label>
										                    <input name="start" type='text' class="form-control" placeholder="开始时间"/>
										                    <span class="input-group-addon">
										                        <i class="fa fa-calendar"></i>
										                    </span>
										                </div>
										            </div>
													<div class="form-group">
										                <div class='input-group date' id='datetimepicker2'>
										                	<label for="script-name" class="sr-only">结束时间</label>
										                    <input name="end" type='text' class="form-control" placeholder="结束时间"/>
										                    <span class="input-group-addon">
										                        <i class="fa fa-calendar"></i>
										                    </span>
										                </div>
										            </div>
								                    <input hidden name="backgroundColor"/>
													<div class="form-group">
														<label for="ref" class="sr-only">关联合同</label>
														<select name="ref" class="form-control">
														</select>
													</div>
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
													<button type="button" class="btn btn-primary">保存事件</button>
													<button type="button" class="btn btn-danger">删除事件</button>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>

	<footer>
		<div class="container">
			<div class="footer-border"></div>
			<div class="row">
				<div class="col-sm-4">
					<p>Copyright  2016 有娱. All Rights Reserved</p>
				</div>
				<div class="col-sm-4">
					<div class="bdsharebuttonbox">
						<a href="#" class="fa fa-qq" data-cmd="tqq"></a>
						<a href="#" class="fa fa-weixin" data-cmd="weixin"></a>
						<a href="#" class="fa fa-weibo" data-cmd="tsina"></a>
					</div>
				</div>
				<div class="col-sm-4">
					<ul class="info">
						<li><span class="fa fa-question-circle"></span><a href="./about.html">关于我们</a></li>
						<li><span class="fa fa-user-plus"></span><a href="./about.html">商务合作</a></li>
						<li><span class="fa fa-info-circle"></span><a href="./about.html">免责声明</a></li>
						<li><span class="fa fa-envelope"></span><a href="./about.html">联系我们</a></li>
						<li><span class="fa fa-h-square"></span><a href="./about.html">帮助</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<!-- 返回顶部悬浮按钮 -->
	<span id="top-link-block" class="hidden">
	    <a href="#top" class="well well-sm" onclick="$('html,body').animate({scrollTop:0},'fast');return false;">
	        <i class="fa fa-arrow-up"></i>返回顶部
	    </a>
	</span>

	<!-- 加载JS -->
	<script src="https://cdn.bootcss.com/jquery/1.12.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="https://cdn.bootcss.com/moment.js/2.11.2/moment.min.js"></script>
	<script type="text/javascript" src="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js" charset="UTF-8"></script>
	<script src="https://cdn.bootcss.com/fullcalendar/2.6.1/fullcalendar.min.js"></script>
	<script src="https://cdn.bootcss.com/fullcalendar/2.6.1/lang/zh-cn.js"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<script src="{% static 'js/contract-info.js' %}"></script>
</body>
</html>